[package]
name = "quasiconfig"
description = """
Quasiconfig is a Blazingly-fast, hyper-portable, and ultra-extensible configuration management system.
"""
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
